name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9,'3.10']

    steps:
    - name: Print current directory
      run: |
        pwd
        ls -al

    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r back-end/requirements.txt
    - name: Run Tests
      run: |
        python back-end/manage.py test
      - name: Deploy to PythonAnywhere
  run: |
    # Install pa_autoconfigure_django.py script
    curl -O https://raw.githubusercontent.com/pythonanywhere/helper_scripts/master/bash/pa_autoconfigure_django.py
    chmod +x pa_autoconfigure_django.py

    # Deploy using the script
    ./pa_autoconfigure_django.py --nuke ${{ s4lent3 }}.pythonanywhere.com --branch=Sprint2
  env:
    API_TOKEN: ${{ aa4b204afc1ad7f6bac389ce6a6e8690b77f119e }}

